function cost = evaluate_theoretical_cost(E, D)
%EVALUATE_THEORETICAL_COST Compute the theoretical implementation cost
% using the cost model adopted in the paper.
%
% Input:
%   E : integer exponent vector
%   D : fractional-width offset vector, where total word length is E + D
%
% Output:
%   cost : theoretical computational cost
%
% The cost structure matches the matrix-polynomial benchmark graph.

cost = ...
    (E(1)+D(1))*(E(3)+D(3)) + ...
    (E(1)+D(1))*(E(4)+D(4)) + ...
    (E(2)+D(2))*(E(3)+D(3)) + ...
    (E(2)+D(2))*(E(4)+D(4)) + ...
    (E(5)+D(5))*(E(9)+D(9)) + ...
    (E(6)+D(6))*(E(10)+D(10)) + ...
    (E(7)+D(7))*(E(9)+D(9)) + ...
    (E(8)+D(8))*(E(10)+D(10)) + ...
    max(E(11), E(13)) + min(D(11), D(13)) + ...
    max(E(12), E(14)) + min(D(12), D(14)) + ...
    (E(15)+D(15))*(E(17)+D(17)) + ...
    (E(16)+D(16))*(E(18)+D(18)) + ...
    (E(19)+D(19))*(E(21)+D(21)) + ...
    (E(20)+D(20))*(E(22)+D(22)) + ...
    max(E(23), E(24)) + min(D(23), D(24));
end