function solution = solve_fractional_widths_lm(C, cfg)
%SOLVE_FRACTIONAL_WIDTHS_LM Solve the continuous relaxation of the
% bit-width allocation problem using a Lagrange-multiplier formulation.
%
% Input:
%   C   : structure containing first-order error coefficients
%   cfg : configuration structure
%
% Output:
%   solution : symbolic solution returned by VPASOLVE
%
% The equation set directly follows the formulation used in the paper and
% preserves the structural form of the original prototype.

dout = cfg.output_fractional_bits;

initial = ones(1, 25) * cfg.vpasolve_initial_value;
initial(25) = cfg.vpasolve_lambda_init;

syms dx1 dx2 dy1 dy2 dz1 dz2 dz3 dz4 dd1 dd2 de1 de2 ...
     df1 df2 dg1 dg2 dh1 dh2 dk1 da1 da2 db1 db2 dc1 lamd

% -------------------------------------------------------------------------
% Stationary conditions derived from the Lagrangian
% -------------------------------------------------------------------------
eqn1  = dy1 + dy2 == lamd * log(2) * 2^(-dx1) * C.Cx1;
eqn2  = dy1 + dy2 == lamd * log(2) * 2^(-dx2) * C.Cx2;
eqn3  = dx1 + dx2 == lamd * log(2) * 2^(-dy1) * C.Cy1;
eqn4  = dx1 + dx2 == lamd * log(2) * 2^(-dy2) * C.Cy2;

eqn5  = dd1 == lamd * log(2) * 2^(-dz1) * C.Cz1;
eqn6  = dd2 == lamd * log(2) * 2^(-dz2) * C.Cz2;
eqn7  = dd1 == lamd * log(2) * 2^(-dz3) * C.Cz3;
eqn8  = dd2 == lamd * log(2) * 2^(-dz4) * C.Cz4;

eqn9  = 1 == lamd * log(2) * 2^(-de1) * C.Ce1;
eqn10 = 1 == lamd * log(2) * 2^(-de2) * C.Ce2;
eqn11 = 1 == lamd * log(2) * 2^(-df1) * C.Cf1;
eqn12 = 1 == lamd * log(2) * 2^(-df2) * C.Cf2;

eqn13 = dh1 == lamd * log(2) * 2^(-dg1) * C.Cg1;
eqn14 = dh2 == lamd * log(2) * 2^(-dg2) * C.Cg2;
eqn15 = dg1 == lamd * log(2) * 2^(-dh1) * C.Ch1;
eqn16 = dg2 == lamd * log(2) * 2^(-dh2) * C.Ch2;

eqn17 = db1 == lamd * log(2) * 2^(-da1) * C.Ca1;
eqn18 = db2 == lamd * log(2) * 2^(-da2) * C.Ca2;
eqn19 = da1 == lamd * log(2) * 2^(-db1) * C.Cb1;
eqn20 = da2 == lamd * log(2) * 2^(-db2) * C.Cb2;

eqn21 = 1 == lamd * log(2) * 2^(-dk1) * C.Ck1;
eqn22 = 1 == lamd * log(2) * 2^(-dc1) * C.Cc1;

% -------------------------------------------------------------------------
% Global error constraint
% -------------------------------------------------------------------------
eqn23 = ...
    2^(-dx1) * C.Cx1 + ...
    2^(-dx2) * C.Cx2 + ...
    2^(-dy1) * C.Cy1 + ...
    2^(-dy2) * C.Cy2 + ...
    2^(-dz1) * C.Cz1 + ...
    2^(-dz2) * C.Cz2 + ...
    2^(-dz3) * C.Cz3 + ...
    2^(-dz4) * C.Cz4 + ...
    2^(-dd1) * C.Cd1 + ...
    2^(-dd2) * C.Cd2 + ...
    2^(-de1) * C.Ce1 + ...
    2^(-de2) * C.Ce2 + ...
    2^(-df1) * C.Cf1 + ...
    2^(-df2) * C.Cf2 + ...
    2^(-dg1) * C.Cg1 + ...
    2^(-dg2) * C.Cg2 + ...
    2^(-dh1) * C.Ch1 + ...
    2^(-dh2) * C.Ch2 + ...
    2^(-da1) * C.Ca1 + ...
    2^(-da2) * C.Ca2 + ...
    2^(-db1) * C.Cb1 + ...
    2^(-db2) * C.Cb2 + ...
    2^(-dc1) * C.Cc1 + ...
    2^(-dk1) * C.Ck1 == 2^(-dout - 1);

eqn24 = dz1 + dz3 == lamd * log(2) * 2^(-dd1) * C.Cd1;
eqn25 = dz2 + dz4 == lamd * log(2) * 2^(-dd2) * C.Cd2;

vars = [dx1, dx2, dy1, dy2, dz1, dz2, dz3, dz4, dd1, dd2, ...
        de1, de2, df1, df2, dg1, dg2, dh1, dh2, dk1, da1, ...
        da2, db1, db2, dc1, lamd];

solution = vpasolve( ...
    [eqn1, eqn2, eqn3, eqn4, eqn5, eqn6, eqn7, eqn8, eqn9, eqn10, ...
     eqn11, eqn12, eqn13, eqn14, eqn15, eqn16, eqn17, eqn18, eqn19, ...
     eqn20, eqn21, eqn22, eqn23, eqn24, eqn25], ...
    vars, ...
    initial);
end