function aggregate = aggregate_batch_solutions(batch_solution, profile, cfg)
%AGGREGATE_BATCH_SOLUTIONS Consolidate continuous bit-width solutions across
% batches.
%
% The first batch provides the coarse initial solution. Subsequent batches
% can refine the allocation. A sensitivity-weighted update is optionally
% applied to mimic the batch-adaptive philosophy described in the paper.

names = {'x','y','z','k','c','n1','n2','t1','t2','t3','t4'};

D_all = [ ...
    batch_solution.x(:), ...
    batch_solution.y(:), ...
    batch_solution.z(:), ...
    batch_solution.k(:), ...
    batch_solution.c(:), ...
    batch_solution.n1(:), ...
    batch_solution.n2(:), ...
    batch_solution.t1(:), ...
    batch_solution.t2(:), ...
    batch_solution.t3(:), ...
    batch_solution.t4(:)];

C_all = [ ...
    profile.Cx(:), ...
    profile.Cy(:), ...
    profile.Cz(:), ...
    profile.Ck(:), ...
    profile.Cc(:), ...
    profile.Cn1(:), ...
    profile.Cn2(:), ...
    profile.Ct1(:), ...
    profile.Ct2(:), ...
    profile.Ct3(:), ...
    profile.Ct4(:)];

D_ref = D_all(1, :);
C_ref = C_all(1, :);

for i = 2:size(D_all, 1)
    for j = 1:size(D_all, 2)
        if D_all(i, j) > D_ref(j)
            if cfg.enable_sensitivity_weighted_update
                weight = 2 * C_all(i, j) / max(C_ref(j) + C_all(i, j), eps);
                D_ref(j) = D_ref(j) + weight * (D_all(i, j) - D_ref(j));
                if C_all(i, j) > C_ref(j)
                    C_ref(j) = 0.9 * C_ref(j) + 0.1 * C_all(i, j);
                end
            else
                D_ref(j) = D_all(i, j);
                C_ref(j) = max(C_ref(j), C_all(i, j));
            end
        end
    end
end

aggregate = struct();
aggregate.names = names;
aggregate.D_batches = D_all;
aggregate.C_batches = C_all;
aggregate.D_continuous = D_ref;
aggregate.C_updated = C_ref;
aggregate.summary_table = array2table(D_all, 'VariableNames', names);
end